[mongo]
    host = "localhost"
    port = 27017
    database = "jfetcher"

[postgres]
    host = "localhost"
    port = 5432
    user = "postgres"
    password = "postgres"
    database = "jfetcher"

[logging]
    display_level = "DEBUG"
    save_level = "DEBUG"

[notify]
    enabled = true
    host = "localhost"
    port = 8701
    token = ""