jianshu_endpoint = ""

beijiaoyi_token = ""

core_user_slugs = []

[jianshu_postgres]
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
database = "jianshu"

[jpep_postgres]
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
database = "jpep"

[beijiaoyi_postgres]
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
database = "beijiaoyi"
