[jianshu_postgres]
    host = "localhost"
    port = 5432
    user = "postgres"
    password = "postgres"
    database = "jfetcher"

[jpep_postgres]
    host = "localhost"
    port = 5432
    user = "postgres"
    password = "postgres"
    database = "jpep"

[logging]
    host = "localhost"
    port = 5432
    user = "jfetcher"
    password = "jfetcher"
    table = "jfetcher"
    display_level = "DEBUG"
    save_level = "DEBUG"

[notify]
    enabled = true
    host = "localhost"
    port = 8701
    token = ""