[jianshu_postgres]
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
database = "jianshu"

[jpep_postgres]
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
database = "jpep"
