networks:
  mongodb:
    external: true
  prefect:
    external: true

services:
  main:
    image: jfetcher:3.0.0
    container_name: jfetcher-v3
    build: .
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - mongodb
      - prefect
    environment:
      - PYTHONUNBUFFERED=1
      - PREFECT_API_URL=http://prefect:4200/api
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
