[project]
name = "jfetcher"
version = "3.4.1"
description = "简书数据采集工具"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name = "FHU-yezi", email = "yehaowei20060411@qq.com"},
]
requires-python = ">=3.9"
dependencies = [
    "jkit>=3.0.0a16",
    "prefect<3.0.0",
    "psycopg[binary]>=3.2.0",
    "sshared[config,mongo,postgres]>=0.11.0",
]

[tool.uv]
dev-dependencies = [
    "pyright>=1.1.0",
    "ruff>=0.6.0",
]

[tool.ruff]
target-version = "py39"
lint.select = [
    "A", "ANN", "ARG", "ASYNC", "B",
    "BLE", "C4", "E", "F", "I",
    "ICN", "ISC", "N", "PERF", "PIE",
    "PT", "Q", "RET", "RSE", "RUF",
    "S", "SIM", "SLOT", "TCH", "UP",
    "W"
]
lint.ignore = ["ANN101", "ANN102", "ISC001", "RUF001", "RUF002", "RUF003"]
