[tool.poetry]
name = "JFetcher"
version = "0.2.2"
description = "简书数据采集工具"
authors = ["FHU-yezi <yehaowei20060411@qq.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
APScheduler = "^3.9.1"
PyYAML = "^6.0"
pymongo = "^4.1.1"
JianshuResearchTools = "2.10.0"

[tool.poetry.dev-dependencies]
mypy = "^0.961"
yapf = "^0.32.0"
flake8 = "^4.0.1"
types-PyYAML = "^6.0.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
