[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
prefect = "^2.19.0"
jkit = "^3.0.0a16"
sshared = { version = "^0.9.0", extras = ["config", "mongo"] }

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.0"
pyright = "^1.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]

target-version = "py38"

lint.select = [
    "A", "ANN", "ARG", "ASYNC", "B",
    "BLE", "C4", "E", "F", "I",
    "ICN", "ISC", "N", "PIE", "PT",
    "Q", "RET", "RSE", "RUF", "S",
    "SIM", "SLOT", "TCH", "UP", "W"
]
lint.ignore = ["ANN101", "ANN102", "ISC001", "RUF001", "RUF002", "RUF003"]