[project]
name = "JFetcher"
version = "3.3.0"
description = "简书数据采集工具"
requires-python = ">=3.8"
dependencies = [
    "prefect>=2.20.3",
    "jkit>=3.0.0a16",
    "sshared[config,mongo]>=0.9.0",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.3",
    "pyright>=1.1.378",
]

[tool.ruff]
target-version = "py38"
lint.select = [
    "A", "ANN", "ARG", "ASYNC", "B",
    "BLE", "C4", "E", "F", "I",
    "ICN", "ISC", "N", "PIE", "PT",
    "Q", "RET", "RSE", "RUF", "S",
    "SIM", "SLOT", "TCH", "UP", "W"
]
lint.ignore = ["ANN101", "ANN102", "ISC001", "RUF001", "RUF002", "RUF003"]